name: turnix_dart
description: >
  A Dart SDK for fetching WebRTC ICE (STUN/TURN) credentials
  from the Turnix.io API, with support for advanced options
  like regions, TTL, client IP, and per-call parameters.
version: 0.1.6
homepage: https://turnix.io
repository: https://github.com/turnixio/turnix_dart
issue_tracker: https://github.com/turnixio/turnix_dart/issues

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  http: ^1.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
